# Generated by Django 3.2 on 2024-06-02 07:22

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRunTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.TimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='uploadpost',
            options={'verbose_name': '文件路径', 'verbose_name_plural': '文件路径'},
        ),
    ]
