# Generated by Django 3.2 on 2024-06-02 07:30
from datetime import datetime

from django.db import migrations, models


def add_initial_data(apps, schema_editor):
    model = apps.get_model('common', 'ServiceRunTime')
    model.objects.create(total=datetime.now())
    print(model)


class Migration(migrations.Migration):
    dependencies = [
        ('common', '0002_auto_20240602_1522'),
    ]

    operations = [
        # migrations.RunPython(add_initial_data),
        migrations.AlterField(
            model_name='serviceruntime',
            name='total',
            field=models.DateTimeField(),
        ),
    ]
