# Generated by Django 4.2.11 on 2024-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_content_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='名称')),
                ('path', models.FilePathField(verbose_name='文件路径')),
            ],
            options={
                'verbose_name': '下载文件',
                'verbose_name_plural': '下载文件',
            },
        ),
    ]
