# Generated by Django 4.2.11 on 2024-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='path',
            field=models.CharField(max_length=260, verbose_name='文件路径'),
        ),
    ]
