# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_tab_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartTabControl(object):
    def setupUi(self, StartTabControl):
        StartTabControl.setObjectName("StartTabControl")
        StartTabControl.resize(400, 300)
        self.widget = QtWidgets.QWidget(StartTabControl)
        self.widget.setGeometry(QtCore.QRect(80, 100, 231, 101))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)

        self.retranslateUi(StartTabControl)
        QtCore.QMetaObject.connectSlotsByName(StartTabControl)

    def retranslateUi(self, StartTabControl):
        _translate = QtCore.QCoreApplication.translate
        StartTabControl.setWindowTitle(_translate("StartTabControl", "Form"))
        self.pushButton_3.setText(_translate("StartTabControl", "PushButton"))
        self.pushButton_5.setText(_translate("StartTabControl", "PushButton"))
        self.pushButton_4.setText(_translate("StartTabControl", "PushButton"))
        self.pushButton_6.setText(_translate("StartTabControl", "PushButton"))
