# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CustomDockWidget(QtWidgets.QDockWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def _resize_based_on_scale(self, size, old_size, src_size):
        # 小于零代表刚刚启动，呃，为什么刚刚启动小于 0 ？
        if old_size.width() < 0:
            return src_size
        w_scale = size.width() / old_size.width()
        h_scale = size.height() / old_size.height()
        print(w_scale,h_scale)
        return QtCore.QSize(src_size.width() * w_scale, src_size.height() * h_scale)

    def resizeEvent(self, event):
        super().resizeEvent(event)
        for child in self.findChildren(QtWidgets.QWidget):
            child.resize(self._resize_based_on_scale(
                event.size(),
                event.oldSize(),
                child.size()
            ))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 911, 621))
        self.layoutWidget.setObjectName("layoutWidget")
        self.central_grid_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.central_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.central_grid_layout.setObjectName("central_grid_layout")
        self.tab_widget = QtWidgets.QTabWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.tab_widget.setFont(font)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.undoView = QtWidgets.QUndoView(self.tab)
        self.undoView.setGeometry(QtCore.QRect(80, 70, 256, 192))
        self.undoView.setObjectName("undoView")
        self.tab_widget.addTab(self.tab, "")
        self.central_grid_layout.addWidget(self.tab_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_2 = CustomDockWidget(MainWindow)
        self.dockWidget_2.setMaximumSize(QtCore.QSize(524287, 627))
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents_2)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 191, 191))
        self.treeView.setObjectName("treeView")
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("MainWindow", "开始"))
