# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 241))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.resultText = QtWidgets.QTextEdit(self.groupBox)
        self.resultText.setGeometry(QtCore.QRect(0, 60, 381, 181))
        self.resultText.setObjectName("resultText")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 31, 16))
        self.label.setObjectName("label")
        self.weatherComboBox = QtWidgets.QComboBox(self.groupBox)
        self.weatherComboBox.setGeometry(QtCore.QRect(90, 30, 191, 22))
        self.weatherComboBox.setObjectName("weatherComboBox")
        self.queryButton = QtWidgets.QPushButton(Form)
        self.queryButton.setGeometry(QtCore.QRect(70, 260, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.queryButton.setFont(font)
        self.queryButton.setObjectName("queryButton")
        self.clearButton = QtWidgets.QPushButton(Form)
        self.clearButton.setGeometry(QtCore.QRect(230, 260, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "查询城市天气"))
        self.label.setText(_translate("Form", "城市"))
        self.queryButton.setText(_translate("Form", "查询"))
        self.clearButton.setText(_translate("Form", "清空"))
