# Generated by Django 4.2.11 on 2024-05-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_html',
            field=models.CharField(blank=True, editable=False, max_length=2000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(help_text='内容支持 MarkDown 格式', max_length=2000, verbose_name='内容'),
        ),
    ]
