# Generated by Django 4.2.11 on 2024-05-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_content_html_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='佚名', max_length=200, verbose_name='昵称'),
        ),
    ]
